- name: Add Node.js repository key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add Node.js apt repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main
    state: present

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes
