- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy Nginx config for Moassel
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/moassel.conf
    owner: root
    group: root
    mode: 0644

- name: Enable Nginx config
  file:
    src: /etc/nginx/sites-available/moassel.conf
    dest: /etc/nginx/sites-enabled/moassel.conf
    state: link
    force: yes

- name: Enable and start Nginx
  service:
    name: nginx
    enabled: yes
    state: started

- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded
